### ISSUE TITLE
README does not explain how the aggregated report is generated

### ISSUE THREAD

**Issue by dberhane** [18F/analytics-reporter#174]
We are a big fun of your analytics project, "analytics.usa.gov" and we are keen to use it for our websites. We have now started the testing phase on a staging server.

We have successfully managed in enabling the site specific dashboard reports. But we are not sure how to generate the aggregated dashboard report. We've gone through your github code repo but we could not find references on how the aggregated reports are generated.

There is a reference "source $HOME/envs/projects/dap-1.env" in the file "https://github.com/18F/analytics-reporter/blob/master/deploy/realtime.sh" which refers to some environmental settings but could not find the source for "dap-1.env" which may have given us an idea how the aggregated reports are generated from Google Analytics.

We would be very grateful if your help.

**Comment by tdlowden** [comment]
Hey @dberhane, thanks for flagging this. The aggregated dashboard report actually comes from an aggregated view within Google Analytics, so it doesn't depend on any of the agency-specific reports. All our data actually pours into one GA account; in our GA structure, we have views for the agencies (with regex filters to pass that agency's domains) and a "master" view, which doesn't filter by domain. So the "all participating websites page" is populated with reports from API calls to the already aggregated GA view. Hope that helps.

Unfortunately, I'm of no use for methods to do the aggregation yourself, but maybe others can jump in with ideas or what they've done.

**Comment by dberhane** [comment]
Thank you @tdlowden for your prompt response. We will consider adding an additional GA tracking ID for all our websites to have the aggregated view as you've suggested, but we are not sure whether we will hit the quota limit of 10 million sessions per tracking ID per month.

I've also discovered a feature called Roll-Up Reporting (https://support.google.com/analytics/answer/6096167?hl=en) which allows you to aggregate data unfortunately it is only available to Google Anaytics Premium which we do not subscribe to.

Yes, it would be great to know if there are easier ways to aggregate the data at the node.js app level.

**Comment by laurenancona** [comment]
@dberhane I know that the GDS ([gov.uk](https://gov.uk)) Performance Platform _does_ aggregate data from many disparate Google Analytics properties (among other resources). It's been a while since I investigated, but some detail is available [here](https://github.com/alphagov/performanceplatform-collector) and via their [blog](https://gdsdata.blog.gov.uk/category/performance-platform/).

**Comment by konklone** [comment]
@dberhane I'm going to close the issue, since I think this is more of an upstream GA configuration thing than an analytics-reporter thing. But thanks for flagging the ambiguity there -- analytics.usa.gov does rely on a GA Premium account and the associated quotas, which is a reflection of its size and scope.
