### ISSUE TITLE
Bulk, dated snapshots

### ISSUE THREAD

**Issue by konklone** [18F/analytics-reporter#52]
We're currently overwriting JSON files in place every minute and every day.

We should also, as a byproduct, save time/date versioned JSON files so that anyone (ourselves included) can use the bulk data at any time to produce reports other than the ones we query Google for directly.

**Comment by rebeccawilliams** [comment]
+ 1

**Comment by gbinal** [comment]
The API we're working to build (https://github.com/18F/analytics-reporter/issues/194) should accomplish this goal.  I'm going to go ahead and close this in anticipation of that.

**Comment by sawyerh** [comment]
In case others come across this in their hunt for historical analytics.usa.gov data beyond before 2017:

It looks like, with a little bit of source code searching, you can find historical data through the Wayback machine. The pages won't render the data, because JavaScript, but if you look at the source code you should be able to find links to the JSON data download links, which are also archived by the Wayback machine 🎊 

For example: https://web.archive.org/web/20150411075559/https://analytics.usa.gov/data/live/devices.json

**Comment by konklone** [comment]
@gbinal Did the API ever launch publicly? I don't see it linked from the main dashboard.

**Comment by tdlowden** [comment]
@konklone we never made a formal public announcement. That said, it'd be worth a link in the footer with a caveat that it's pretty nascent.

**Comment by tdlowden** [comment]
I attempted it over here https://github.com/18F/analytics.usa.gov/pull/510
