### ISSUE TITLE
Top Downloads data Not Updating in 7 and 30 days

### ISSUE THREAD

**Issue by smarina04** [18F/analytics-reporter#757]
I noticed that we are showing the same real-time/NOW data for Top Downloads. When reading closer, I saw that it says under the title "Total file downloads yesterday on government hostnames." Can we confirm what data range that is? Like, why is it yesterday vs. now? And can we pull Total Downloads for 7 and 30 days for consistency with top pages?

![Image](https://github.com/18F/analytics-reporter/assets/3287495/5a71e2f8-2664-469e-948e-179ead6ec3f1)

**Comment by scottqueen-bixal** [comment]
@smarina04 the Top Downloads chart is not part of the Now - 7days - 30days tab component or logic.  I could see how a user might arrive to that consideration since there is nothing dividing there except a bit of white space.  Perhaps it needs a horizontal line accross the top to better separate those two UI interactions more visually.

Some additional information
- We use https://analytics.usa.gov/data/live/top-downloads-yesterday.json to populate the data there.

**Comment by smarina04** [comment]
I see, ok, then we need to add "Yesterday" in the Top Downloads" Sub-title @nick-mon1 . Thank you for the clarification @scottqueen-bixal

**Comment by nick-mon1** [comment]
@smarina04 Subtitle now reads "Top Downloads Yesterday".

![Image](https://github.com/18F/analytics-reporter/assets/104778659/36eeaf21-0da5-4355-abb7-1d1445f7e535)

**Comment by smarina04** [comment]
Thank you
