### ISSUE TITLE
petitions URL trailing text getting stripped in link on homepage

### ISSUE THREAD

**Issue by lheyman** [18F/analytics-reporter#84]
There's is a We The People petition listed in the "Top 20 Pages" list that appears to be getting some text stripped out, causing an improper link.
This:
https://petitions.whitehouse.gov//petition/take-out-alejandro-garc%C3%ADa-padilla-governorship-puerto-rico-now/B0jgB8Sv
is being turned in to this in the top 20 list:
https://petitions.whitehouse.gov//petition/take-out-alejandro-garc%C3%ADa-padilla-governorship-puerto-rico-now/

**Comment by lheyman** [comment]
@konklone

**Comment by konklone** [comment]
OK OK, I'm on it! :)

**Comment by konklone** [comment]
Ahhh @lheyman, this is the more general problem of how the DAP lower-cases URIs:

https://github.com/GSA/DAP-Gov-wide-GA-Code/issues/10

We're stripping off the text because the lower-cased URI is a 404, and this is a feasible way of making it not a 404. We can't guess what the original casing was from the lower-cased version.

This is a DAP bug, and one I'd like to see fixed ASAP too. @tdlowden can speak to a timeline on that. In the meantime, can you recommend a better strategy for us to handle this situation? Is it possible for you to make WHP URLs case-insensitive? Is it a practical issue that we're sending you URLs without the little hash on the end?

**Comment by lheyman** [comment]
yes, that's the issue, the url without the hash is not a working page (for now), if you hit it you see the petition but can't sign it (the signature form throws an error).

That said, we're working on removing the need for the hashes, so if you think this fix will take more than a few days you can probably close this.

**Comment by tdlowden** [comment]
@lheyman ... @smarina04 and I are working on this.

**Comment by konklone** [comment]
I think this problem is moot now? Feel free to re-open if not.
