### ISSUE TITLE
Automate Data Snapshots to www.gsa.gov/data.json 

### ISSUE THREAD

**Issue by rebeccawilliams** [18F/analytics-reporter#86]
So this data will also be available ideally in daily updated bulk (see #52) on Data.gov and cataloged in accordance with the Federal Open Data Policy.

**Comment by konklone** [comment]
It absolutely should be. This issue is better suited for the [analytics.usa.gov repo](https://github.com/GSA/analytics.usa.gov) , and we discussed it a bit in https://github.com/GSA/analytics.usa.gov/issues/117. 

As I mentioned there, I kicked off an email thread a couple months ago to connect the GSA `/data.json` team to the DAP -- I think that's well worth rekindling.

I've reopened and renamed https://github.com/GSA/analytics.usa.gov/issues/117 to track completion of this task.
